version: '3.8'

services:
  user-register:
    container_name: devel-user_register
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=devel-user_register
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
